🏆 NumPy Mastery — Final Challenge 2
Scenario:
You are analyzing weekly rainfall data (in mm) from 4 different regions over 5 weeks.
Your goal is to generate, process, and analyze this dataset using only NumPy.

In [1]:
import numpy as np

Step 1 — Data Creation
Generate a 4x5 array of random integers between 50 and 200 (representing rainfall in mm).
Print the array with a clear label.

In [3]:
rainfall = np.random.randint(50,200,20)
rainfall = rainfall.reshape(4,5)
print(rainfall)

[[ 85 144 113 156  50]
 [190 133 144 141 182]
 [143 191 160  52  54]
 [ 64 156 171  64  77]]


Step 2 — Basic Info

In [7]:
# Print the shape, size, and data type of the array.
print(f"Shape:{rainfall.shape}")
print(f"Size:{rainfall.size}")
print(f"Data_Type:{rainfall.dtype}")
print(rainfall.flatten())
# Flatten the array into 1D and print it.

Shape:(4, 5)
Size:20
Data_Type:int32
[ 85 144 113 156  50 190 133 144 141 182 143 191 160  52  54  64 156 171
  64  77]


Step 3 — Slicing & Indexing

In [10]:
# Print all rainfall data for the second region.
print(rainfall)
print(rainfall[1])
# Print rainfall amounts for the last 2 weeks in the third region.
print(rainfall[2,3:])
# Print the rainfall in the fourth region during week 3.
print(rainfall[3,2])

[[ 85 144 113 156  50]
 [190 133 144 141 182]
 [143 191 160  52  54]
 [ 64 156 171  64  77]]
[190 133 144 141 182]
[52 54]
171


Step 4 — Statistics

In [ ]:
# Find and print the overall mean rainfall.
print(rainfall.mean())

# Print the max and min rainfall for each region (row-wise).
visual = "Region1,Region2,Region3,Region4"
print(visual)
max_output = ",".join(f"{value}"for value in rainfall.max(axis = 1))
print(max_output)
min_output = ",".join(f"{value}"for value in rainfall.min(axis = 1))
print(min_output)
# Find the variance for each region.
var = ",".join(f"{value}"for value in rainfall.var(axis = 1))
print(var)
print("Week1,Week2,Week3,Week4,Week5")
# Calculate the average rainfall per week (column-wise mean).
average = ",".join(f"{value}"for value in rainfall.mean(axis = 0))
print(average)


123.5
Region1,Region2,Region3,Region4
156,190,191,171
50,133,52,64
1501.04,542.0,3230.0,2218.64
Week1,Week2,Week3,Week4,Week5
120.5,156.0,147.0,103.25,90.75


Step 5 — Boolean Filtering

In [35]:
# Extract and print all rainfall amounts above 150 mm.
print(rainfall[rainfall>150])
# Extract and print all rainfall amounts that are divisible by 5.
print(rainfall[rainfall%5 == 0])

[156 190 182 191 160 156 171]
[ 85  50 190 160]


Step 6 — Broadcasting

In [ ]:
# Assume the rain gauges underreported by 10 mm — add 10 to all readings and print the corrected data.
print(rainfall+10)
# A weather anomaly caused a weekly offset: add [5, -5, 0, 10, -10] (week-wise adjustment) to the dataset using broadcasting.
print(rainfall + np.array([5, -5, 0, 10, -10]).reshape(1,5))

[[ 95 154 123 166  60]
 [200 143 154 151 192]
 [153 201 170  62  64]
 [ 74 166 181  74  87]]
[[ 85 144 113 156  50]
 [190 133 144 141 182]
 [143 191 160  52  54]
 [ 64 156 171  64  77]]
[[ 90 139 113 166  40]
 [195 128 144 151 172]
 [148 186 160  62  44]
 [ 69 151 171  74  67]]


Step 7 — Views vs Copies


In [50]:
# Create a view of the first region’s rainfall for the first 3 weeks, modify one value, and show the change in the original array.
view = rainfall[0,:3]
print(view)
view[2] = 69
print(rainfall)
# Create a copy of the last region’s last 3 weeks, modify one value, and show that the original is unchanged.
copy = rainfall[3,2:].copy()
print(copy)
copy[2] = 6969
print(rainfall)

[ 85 144  69]
[[ 85 144  69 156  50]
 [190 133 144 141 182]
 [143 191 160  52  54]
 [ 64 156 171  64  77]]
[171  64  77]
[[ 85 144  69 156  50]
 [190 133 144 141 182]
 [143 191 160  52  54]
 [ 64 156 171  64  77]]
