In [30]:
import numpy as np
#new cwll->esc+B

In [31]:
#create a 1D NumPy array and its type
data = np.array([5, 10, 15, 20])
print(data)
print(data.dtype)

[ 5 10 15 20]
int64


In [32]:
#Create a 3×3 matrix of all zeros
# Create a 3×3 matrix of all ones
# Print both matrices
Zero_Matrix = np.zeros((3,3))
One_Matrix = np.ones((3,3))
print(f"Zero Matrice:{Zero_Matrix}")
print(f"One Matrice:{One_Matrix}")

Zero Matrice:[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
One Matrice:[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [33]:
#Create an Array of Even Numbers
Even = np.arange(2,101,2)
visual = ",".join(f"{value}" for value in Even)
print(visual)
print(Even.shape)

2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,64,66,68,70,72,74,76,78,80,82,84,86,88,90,92,94,96,98,100
(50,)


In [34]:
#Check Shape, Dimensions, Size, Data Type
# | Function      | Meaning                               |
# | ------------- | ------------------------------------- |
# | `array.shape` | Tuple of (rows, columns)              |
# | `array.ndim`  | Number of dimensions (1D, 2D, etc.)   |
# | `array.size`  | Total elements (e.g., 2×3 = 6)        |
# | `array.dtype` | Type of elements (`int32`, `float64`) |

Cubes = np.array([i**3 for i in range(1, 11)])  # Cubes from 1 to 10
print(f"Cubes = {Cubes}")
print(f"Cubes is {Cubes.ndim}D array of {Cubes.size} elements. The datatype is {Cubes.dtype}")
Cubes_2D = Cubes.reshape(2, 5)
print("Cubes_2D")
print(Cubes_2D)
print(f"Cubes_2D is {Cubes_2D.ndim}D array with {Cubes_2D.shape[0]} rows and {Cubes_2D.shape[1]} columns.")
print(f"The datatype is {Cubes.dtype}.")    


Cubes = [   1    8   27   64  125  216  343  512  729 1000]
Cubes is 1D array of 10 elements. The datatype is int64
Cubes_2D
[[   1    8   27   64  125]
 [ 216  343  512  729 1000]]
Cubes_2D is 2D array with 2 rows and 5 columns.
The datatype is int64.


In [35]:
# Indexing Elements in Arrays
# Create a 2D array like [[10, 20, 30], [40, 50, 60]]
array = np.arange(10,70,10)
array = array.reshape(2,3)
# Access and print:
print(array[0,1])
# The element at 1st row, 2nd column (should give 20)
print(array[1,2])
# The element at 2nd row, 3rd column (should give 60)

20
60


In [36]:
# Slicing Subsets from Arrays
# | Syntax                         | Meaning                           |
# | ------------------------------ | --------------------------------- |
# | `array[start:stop]`            | Basic slicing for 1D array        |
# | `array[row_index, start:stop]` | Slice part of a row               |
# | `array[start_row:stop_row, :]` | Slice multiple rows (all columns) |
# | `array[:, start_col:stop_col]` | Slice multiple columns (all rows) |

print(array[0,1:])
# All values in the first row, from second column onward
print(array[:,1])
# All values in the second column, from both rows



[20 30]
[20 50]


In [37]:
# Add 5 to every element

# Multiply every element by 2

# Square each element

# Print all three results to verify!
array = np.array([10, 20, 30])
array1 = array+5
print(array1)
array2 = array*2
print(array2)
array3 = array**2
print(array3)

[15 25 35]
[20 40 60]
[100 400 900]


In [38]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
# Then:
# Print the mean of x
print(x.mean())
# Compute and print the dot product of x and y
print(np.dot(x,y))

2.0
140


In [39]:
# Create a 1D array with values from 0 to 11
array = np.arange(0,12,1)
# Reshape it into 3 rows and 4 columns
reshaped_array = array.reshape(3,4)
# Print both:
# The reshaped matrix
print(reshaped_array)

# Its transpose
transpose = reshaped_array.transpose()
print(transpose)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [40]:
# Generate a 1D array of 5 random floats between 0 and 1
OneD_array = np.random.rand(5)
# print(OneD_array)
# Generate a 3x3 array of random integers from 10 to 99
array = np.random.randint(10,99,9)
array = array.reshape(3,3)
# Calculate and print:
# Sum
print(array.sum())
# Max
print(array.max())
# Min
print(array.min())
# Standard Deviation (std)
print(array.std())
# Mean
print(array.mean())

530
92
16
24.066779521639575
58.888888888888886


✅ Step 7: Boolean Masking & Filtering

In [41]:

# Create a NumPy array of 10 random integers between 1 and 100
numpy_array = np.random.randint(1,100,10)
print(numpy_array)
# Use boolean masking to:

# Extract all values greater than 50
greater_than_50 = numpy_array > 50
print(numpy_array[greater_than_50])
# Extract all values less than or equal to 30
less_than_equal_30 = numpy_array <= 30
print(numpy_array[less_than_equal_30])
# Extract all even numbers
print(numpy_array[numpy_array%2 == 0])
# Extract all odd numbers
print(numpy_array[numpy_array%2 != 0])

[55 36 32  1 81 24 69 47 50 18]
[55 81 69]
[ 1 24 18]
[36 32 24 50 18]
[55  1 81 69 47]


In [ ]:
# Create a 3x4 NumPy array with any values (you can use np.arange() or randint()).
array = np.random.randint(1,100,12)
array = array.reshape(3,4)
print(array)
# Print:
# Row-wise sum (axis=1)
print(array.sum(axis = 1))
# Column-wise sum (axis=0)
print(array.sum(axis = 0))
# Row-wise mean
print(array.mean(axis = 1))
# Column-wise max
print(array.max(axis = 0))
# Column-wise standard deviation
print(array.std(axis = 0))

[[84 83 32 12]
 [ 4 65  4 99]
 [84 49 94 13]]
[211 172 240]
[172 197 130 124]
[52.75 43.   60.  ]
[84 83 94 99]
[37.71236166 13.88844444 37.60614607 40.77853466]


Step 9: NumPy Broadcasting

In [52]:
# Create a 2D array:
print("2D Array")
array_2D = np.random.randint(1,100,6)
array_2D = array_2D.reshape(2,3)
print(array_2D)
# Create a 1D array:
print("1D Array")
array_1D = np.random.randint(1,100,3)
array_1D = array_1D.reshape(1,3)
print(array_1D)
# Add them together and print the result.
result = array_1D + array_2D
print(result)
# Then try subtracting a 1D row vector like [1, 1, 1] from the original 2D array.
result = array_2D - array_1D
print(result)

2D Array
[[29 98 99]
 [99 84 97]]
1D Array
[[32 51 62]]
[[ 61 149 161]
 [131 135 159]]
[[-3 47 37]
 [67 33 35]]



✅ Step 10: Copy vs View in NumPy
This step is about understanding whether you're changing the original array or just a reference to it.

🔍 Concept:
A copy creates a new, independent array.

A view is just a reference (or window) to the same data in memory.

In [59]:
# ✅ Exercise Idea:
# 🧩 Part 1: Using a View
# Create an array with at least 6 elements.
array_view = np.random.randint(1,100,6)

# Slice a portion of the array — for example, take index 2 to 5. This slice is a view.
View = array_view[2:]
# Print both the original array and the view.
print("Array: ",array_view)
print("View: ",View)
# Modify a value inside the view — change one of the elements.
View[2] = 69
# Print the original array again — you’ll notice that the change affected the original array too.
print("Array: ",array_view)
# 📤 Part 2: Using a Copy
# Repeat steps 1 and 2 — create the same array and slice a portion.
array_copy = np.random.randint(1,100,6)
# This time, create a copy of that slice.
Copy = array_copy[2:].copy()
# Modify the copy.
Copy[0] = 58
# Print both the original array and the modified copy.
print("Array: ",array_copy)
print("Copy: ",Copy)
# You’ll see that the original array remains unchanged — because you were working on a copy.

Array:  [44 24 95 24 78 29]
View:  [95 24 78 29]
Array:  [44 24 95 24 69 29]
Array:  [27  3 71 29 72  1]
Copy:  [58 29 72  1]
